name: Daily Rail Scraper

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install webdriver-manager
        
    - name: Run scraper
      run: python RailScraper.py
      
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add timetable.html timetable_data.json
        git diff --staged --quiet || git commit -m "Update timetables - $(date)"
        git push
